### ISSUE TITLE
Remove Mare Synchronos

### ISSUE THREAD

**Issue by rootdarkarchon** [Akurosia/MyCustomDalamudPluginRepoCollection#17]
Please remove Mare Synchronos and associated forks from your repository. As the main hoster for the Mare service I do not wish for the plugin to be rehosted and run from unknown repositories to minimize the impact of unofficial clients against my hosted service.

**Comment by rootdarkarchon** [comment]
the offending URLs are

https://raw.githubusercontent.com/eqbot/DalamudPluginRepo/master/pluginmaster.json
https://raw.githubusercontent.com/Penumbra-Sync/repo/main/plogonmaster.json

as they have not been added to removed_on_request.json the plugin has reappeared after the automatic scan.

**Comment by Akurosia** [comment]
just FYI if more of your repos appear, that will be most likly due to the fact that they are part of https://xivplugins.com/dalamud-plugins from where i grab 99% of the links found in here as i use this side as a basis to get new repositories.

if you have any other repo than these 3. please let me know so i can remove them in advance:
    "https://raw.githubusercontent.com/rootdarkarchon/Penumbra/master/repo.json", 
    "https://raw.githubusercontent.com/eqbot/DalamudPluginRepo/master/pluginmaster.json",
    "https://raw.githubusercontent.com/Penumbra-Sync/repo/main/plogonmaster.json",
