### ISSUE TITLE
Not really an issue with the repo.

### ISSUE THREAD

**Issue by Battler624** [Akurosia/MyCustomDalamudPluginRepoCollection#18]
I have an issue, but I don't think its related to the repo but maybe you could automatically change stuff, so these things won't happen.

The issue for example I want to use penumbra, but if I install it from your repo (the xivdev version) I get a notification that there is an update, and it updates to the Arkker version.
from this 
https://github.com/xivdev/Penumbra
to this
https://github.com/aRkker/DalamudPlugins

**Comment by Akurosia** [comment]
The root cause of the problem is, that aRkkter uses the same internal name for penumbra as the "official" penumbra one.
I could add a special case but this would not fix the problem itself as it would reappear everytime a different user does the same stuff again.
I was thinking about to fix some plugins (like the big known one like penumbra, glamourer etc) but on the other hand it might not be a good alternative.
The easiest solution would be contacting aRkkter and ask if it would be possible to change the internal name (as they changed the display name as well).

**Comment by Akurosia** [comment]
ok for penumbra itself i put in an extra check for the moment. You would need to remove it and reinstall it to get back to the original version
